#!/bin/bash
#

function display() {
        # $1=name $2=value $3=red_limit $4=minimal_show_limit $5=unit $6=after
        local great=">"
        if [[ -n "$2" && "$2" > "0" && (( "${2%.*}" -ge "$4" )) ]]; then
                printf "%-14s" "$1"
                if awk "BEGIN{exit ! ($2 $great $3)}"; then echo -ne "\e[0;91m $2"; else echo -ne "\e[0;92m $2"; fi
                printf "%-1s\x1B[0m" "$5"
                printf "%-11s\t" "$6"
                return 1
        fi
}

function storage_info() {
        RootInfo=$(df -h /)
        root_usage=$(awk '/\// {print $(NF-1)}' <<<${RootInfo} | sed 's/%//g')
        root_total=$(awk '/\// {print $(NF-4)}' <<<${RootInfo})
}

storage_info
critical_load=80

UPTIME=$(LC_ALL=C uptime)
UPT1=${UPTIME#*'up '}
UPT2=${UPT1%'user'*}
time=${UPT2%','*}
time=${time//','}
time=$(echo $time | xargs)
load=${UPTIME#*'load average: '}
load=${load//','}

# Text Color Variables http://misc.flogisoft.com/bash/tip_colors_and_formatting
tcLtG="\033[00;37m" # LIGHT GRAY
tcDkG="\033[01;30m" # DARK GRAY
tcLtR="\033[01;31m" # LIGHT RED
tcLtGRN="\033[01;32m" # LIGHT GREEN
tcLtBL="\033[01;34m" # LIGHT BLUE
tcLtP="\033[01;35m" # LIGHT PURPLE
tcLtC="\033[01;36m" # LIGHT CYAN
tcW="\033[01;37m" # WHITE
tcRESET="\033[0m"
tcORANGE="\033[38;5;209m"

# Time of day
HOUR=$(date +"%H")
if [ $HOUR -lt 12 -a $HOUR -ge 0 ]; then TIME="morning"
elif [ $HOUR -lt 17 -a $HOUR -ge 12 ]; then TIME="afternoon"
else TIME="evening"
fi

# System uptime
uptime=`cat /proc/uptime | cut -f1 -d.`
upDays=$((uptime/60/60/24))
upHours=$((uptime/60/60%24))
upMins=$((uptime/60%60))

# memory
mem_info=$(LC_ALL=C free -w 2>/dev/null | grep "^Mem" || LC_ALL=C free | grep "^Mem")
memory_usage=$(awk '{printf("%.0f",(($2-($4+$6+$7))/$2) * 100)}' <<<${mem_info})
mem_info=$(echo $mem_info | awk '{print $2}')
memory_total=$(( mem_info / 1024 ))

if [[ ${memory_total} -gt 1000 ]]; then
        memory_total=$(awk '{printf("%.2f",$1/1024)}' <<<${memory_total})"G"
else
        memory_total+="M"
fi

ROOT_USED=`df -h / | awk '/\// {print $(NF-1)}'`

# System + Memory
SYS_LOADS=`cat /proc/loadavg | awk '{print $1}'`
SWAP_USED=`free -m | tail -n 1 | awk '{print $3}'`
NUM_PROCS=`ps aux | wc -l`
IPADDRESS=`hostname --all-ip-addresses`

echo -e $tcDkG "==================================================================="
echo -e $tcLtG " Good $TIME ! $tcORANGE IT"
echo -e $tcDkG "==================================================================="
echo -e $tcLtG " Сервер ..."
echo -e $tcDkG "==================================================================="
echo -e $tcLtG " - Hostname............:$tcW `hostname -f`"
echo -e $tcLtG " - IP Address..........:$tcW $IPADDRESS"
echo -e $tcLtG " - Release.............:$tcW $(lsb_release -s -d)"
echo -e $tcLtG " - Kernel..............: `uname -r`"
echo -e $tcLtG " - Users...............: Currently `users | wc -w` user(s) logged on"
echo -e $tcLtG " - Server Time.........: `date`"
echo -e $tcLtG " - System load.........: $SYS_LOADS / $NUM_PROCS processes running"
echo -e $tcLtG " - `display "Memory usage" "$memory_usage" "70" "0" "%" " of ${memory_total}"`"
echo -e $tcLtG " - `display "Usage of /" "$root_usage" "90" "1" "%" " of $root_total"`"
echo -e $tcLtG " - Swap used...........: $SWAP_USED MB"
echo -e $tcLtG " - System uptime.......: $upDays days $upHours hours $upMins minutes"
echo -e $tcDkG "==================================================================="
echo -e $tcRESET ""
